### ISSUE TITLE
Error with closeSocket.on

### ISSUE THREAD

**Issue by stipmonster** [vatesfr/xo-server-auth-ldap#4] opened 2015-05-16 22:11 UTC
If i try to authenticated with ldap credentials using no anonymous bind i get the following error
is this a wrong configuration casing this?

```
/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/client.js:111
  closeSocket.on('close', function onClose(had_err) {
             ^
TypeError: Cannot read property 'on' of undefined
    at setupSocket (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/client.js:111:14)
    at Client._connect (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/client.js:742:3)
    at new Client (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/client.js:247:22)
    at Pool.createClient [as create] (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/pool.js:45:20)
    at Pool._create (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/pooling/lib/pool.js:416:14)
    at Pool.acquire (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/pooling/lib/pool.js:258:14)
    at /xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/lib/client/pool.js:255:22
    at f (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/pooling/node_modules/once/once.js:16:25)
    at end (/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/pooling/lib/pool.js:351:17)
    at process._tickCallback (node.js:355:11)
```

The relevant part of the config
```
plugins:

  auth-ldap:
    uri: "ldaps://domain.example.com"

    checkCertificate: false

    bind:
      dn: 'cn=admin,dc=example,dc=com'
      password: ''

    base: "dc=example,dc=com"
    filter: '(uid={{name}})'
```

**Comment by julien-f** [comment] 2015-05-18 10:37
It seems that this issue is caused by an incompatibility between the LDAP library (see mcavage/node-ldapjs#256) we are using and Node 0.12 (and io.js).
It looks like it will be fixed in the next release of this library (but I don't know when).

I suggest you keep using Node 0.10 for now.

**Comment by julien-f** [comment] 2016-09-01 16:15
If it's still the case, please re-open the issue.

**Closed by julien-f** 2016-09-01 16:15 UTC
Labels: bug
